/**
 * WinSMS
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Winsms) {
      root.Winsms = {};
    }
    root.Winsms.DeletedMessageStatus = factory(root.Winsms.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeletedMessageStatus model module.
   * @module model/DeletedMessageStatus
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeletedMessageStatus</code>.
   * @alias module:model/DeletedMessageStatus
   * @class
   * @param apiMessageId {Number} The WinSMS API Message Id identifying the SMS message. 
   * @param mobileNumber {String} The mobile number of the recipient of the SMS message, using the international E164 (without the plus) format 
   * @param deleted {Boolean} A boolean value indicating whether a scheduled SMS message was successfully deleted 
   * @param deleteError {String} If the ***deleted*** value is false, this will contain an error code indicating the reason for the failure. If the scheduled SMS message was successfully deleted, this value will be blank. 
   * @param creditCost {Number} The number of credits refunded to your account after deleting the scheduled message.  If the deletion was unsuccessful, this value will be 0. 
   */
  var exports = function(apiMessageId, mobileNumber, deleted, deleteError, creditCost) {
    var _this = this;

    _this['apiMessageId'] = apiMessageId;
    _this['mobileNumber'] = mobileNumber;
    _this['deleted'] = deleted;
    _this['deleteError'] = deleteError;
    _this['creditCost'] = creditCost;
  };

  /**
   * Constructs a <code>DeletedMessageStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeletedMessageStatus} obj Optional instance to populate.
   * @return {module:model/DeletedMessageStatus} The populated <code>DeletedMessageStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiMessageId')) {
        obj['apiMessageId'] = ApiClient.convertToType(data['apiMessageId'], 'Number');
      }
      if (data.hasOwnProperty('mobileNumber')) {
        obj['mobileNumber'] = ApiClient.convertToType(data['mobileNumber'], 'String');
      }
      if (data.hasOwnProperty('deleted')) {
        obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
      }
      if (data.hasOwnProperty('deleteError')) {
        obj['deleteError'] = ApiClient.convertToType(data['deleteError'], 'String');
      }
      if (data.hasOwnProperty('creditCost')) {
        obj['creditCost'] = ApiClient.convertToType(data['creditCost'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The WinSMS API Message Id identifying the SMS message. 
   * @member {Number} apiMessageId
   */
  exports.prototype['apiMessageId'] = undefined;
  /**
   * The mobile number of the recipient of the SMS message, using the international E164 (without the plus) format 
   * @member {String} mobileNumber
   */
  exports.prototype['mobileNumber'] = undefined;
  /**
   * A boolean value indicating whether a scheduled SMS message was successfully deleted 
   * @member {Boolean} deleted
   */
  exports.prototype['deleted'] = undefined;
  /**
   * If the ***deleted*** value is false, this will contain an error code indicating the reason for the failure. If the scheduled SMS message was successfully deleted, this value will be blank. 
   * @member {String} deleteError
   */
  exports.prototype['deleteError'] = undefined;
  /**
   * The number of credits refunded to your account after deleting the scheduled message.  If the deletion was unsuccessful, this value will be 0. 
   * @member {Number} creditCost
   */
  exports.prototype['creditCost'] = undefined;



  return exports;
}));


