/**
 * WinSMS
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Winsms) {
      root.Winsms = {};
    }
    root.Winsms.ErrorDetails = factory(root.Winsms.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ErrorDetails model module.
   * @module model/ErrorDetails
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ErrorDetails</code>.
   * @alias module:model/ErrorDetails
   * @class
   * @param timeStamp {String} The date/time the request was processed, in the format YYYYMMDDhhmmssSSS 
   * @param version {String} The current version of the API of the endpoint that was called 
   * @param statusCode {Number} The http status code returned - reflected in the body for convenience 
   * @param errorMessage {String} A plain text description of the error that occurred, and possible solutions if available.  
   */
  var exports = function(timeStamp, version, statusCode, errorMessage) {
    var _this = this;

    _this['timeStamp'] = timeStamp;
    _this['version'] = version;
    _this['statusCode'] = statusCode;
    _this['errorMessage'] = errorMessage;
  };

  /**
   * Constructs a <code>ErrorDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorDetails} obj Optional instance to populate.
   * @return {module:model/ErrorDetails} The populated <code>ErrorDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('timeStamp')) {
        obj['timeStamp'] = ApiClient.convertToType(data['timeStamp'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
      if (data.hasOwnProperty('statusCode')) {
        obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
      }
      if (data.hasOwnProperty('errorMessage')) {
        obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
      }
    }
    return obj;
  }

  /**
   * The date/time the request was processed, in the format YYYYMMDDhhmmssSSS 
   * @member {String} timeStamp
   */
  exports.prototype['timeStamp'] = undefined;
  /**
   * The current version of the API of the endpoint that was called 
   * @member {String} version
   */
  exports.prototype['version'] = undefined;
  /**
   * The http status code returned - reflected in the body for convenience 
   * @member {Number} statusCode
   */
  exports.prototype['statusCode'] = undefined;
  /**
   * A plain text description of the error that occurred, and possible solutions if available.  
   * @member {String} errorMessage
   */
  exports.prototype['errorMessage'] = undefined;



  return exports;
}));


