/**
 * WinSMS
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Winsms) {
      root.Winsms = {};
    }
    root.Winsms.MessageRecipientDetails = factory(root.Winsms.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MessageRecipientDetails model module.
   * @module model/MessageRecipientDetails
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MessageRecipientDetails</code>.
   * @alias module:model/MessageRecipientDetails
   * @class
   * @param mobileNumber {String} A recipient mobile number, using the international E164 (without the plus) format.
   */
  var exports = function(mobileNumber) {
    var _this = this;

    _this['mobileNumber'] = mobileNumber;

  };

  /**
   * Constructs a <code>MessageRecipientDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageRecipientDetails} obj Optional instance to populate.
   * @return {module:model/MessageRecipientDetails} The populated <code>MessageRecipientDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mobileNumber')) {
        obj['mobileNumber'] = ApiClient.convertToType(data['mobileNumber'], 'String');
      }
      if (data.hasOwnProperty('clientMessageId')) {
        obj['clientMessageId'] = ApiClient.convertToType(data['clientMessageId'], 'String');
      }
    }
    return obj;
  }

  /**
   * A recipient mobile number, using the international E164 (without the plus) format.
   * @member {String} mobileNumber
   */
  exports.prototype['mobileNumber'] = undefined;
  /**
   * ***Optional*** - A parameter to identify an individual SMS message recipient on your system. The clientMessageId parameter is NOT saved by the WinSMS API.   The value of the clientMessageId parameter is returned in the ***submittedRecipientResult*** object of the response, allowing you to match a sent message to a returned message result status. 
   * @member {String} clientMessageId
   */
  exports.prototype['clientMessageId'] = undefined;



  return exports;
}));


