/**
 * WinSMS
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IncomingOptoutMessage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IncomingOptoutMessage'));
  } else {
    // Browser globals (root is window)
    if (!root.Winsms) {
      root.Winsms = {};
    }
    root.Winsms.OptoutMessageResponse = factory(root.Winsms.ApiClient, root.Winsms.IncomingOptoutMessage);
  }
}(this, function(ApiClient, IncomingOptoutMessage) {
  'use strict';




  /**
   * The OptoutMessageResponse model module.
   * @module model/OptoutMessageResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OptoutMessageResponse</code>.
   * @alias module:model/OptoutMessageResponse
   * @class
   * @param timeStamp {String} The date/time the request was processed, in the format YYYYMMDDhhmmssSSS
   * @param version {String} The current version of the API of the endpoint that was called
   * @param statusCode {Number} The http status code returned - reflected in the body for convenience
   * @param incomingOptoutMessages {Array.<module:model/IncomingOptoutMessage>} An array of ***incomingOptoutMessage*** objects containing properties of each opt-out message received. 
   */
  var exports = function(timeStamp, version, statusCode, incomingOptoutMessages) {
    var _this = this;

    _this['timeStamp'] = timeStamp;
    _this['version'] = version;
    _this['statusCode'] = statusCode;
    _this['incomingOptoutMessages'] = incomingOptoutMessages;
  };

  /**
   * Constructs a <code>OptoutMessageResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OptoutMessageResponse} obj Optional instance to populate.
   * @return {module:model/OptoutMessageResponse} The populated <code>OptoutMessageResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('timeStamp')) {
        obj['timeStamp'] = ApiClient.convertToType(data['timeStamp'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
      if (data.hasOwnProperty('statusCode')) {
        obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
      }
      if (data.hasOwnProperty('incomingOptoutMessages')) {
        obj['incomingOptoutMessages'] = ApiClient.convertToType(data['incomingOptoutMessages'], [IncomingOptoutMessage]);
      }
    }
    return obj;
  }

  /**
   * The date/time the request was processed, in the format YYYYMMDDhhmmssSSS
   * @member {String} timeStamp
   */
  exports.prototype['timeStamp'] = undefined;
  /**
   * The current version of the API of the endpoint that was called
   * @member {String} version
   */
  exports.prototype['version'] = undefined;
  /**
   * The http status code returned - reflected in the body for convenience
   * @member {Number} statusCode
   */
  exports.prototype['statusCode'] = undefined;
  /**
   * An array of ***incomingOptoutMessage*** objects containing properties of each opt-out message received. 
   * @member {Array.<module:model/IncomingOptoutMessage>} incomingOptoutMessages
   */
  exports.prototype['incomingOptoutMessages'] = undefined;



  return exports;
}));


