/**
 * WinSMS
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Winsms) {
      root.Winsms = {};
    }
    root.Winsms.ScheduledMessage = factory(root.Winsms.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ScheduledMessage model module.
   * @module model/ScheduledMessage
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ScheduledMessage</code>.
   * @alias module:model/ScheduledMessage
   * @class
   * @param apiMessageId {Number} The WinSMS API Message Id identifying the SMS message.
   * @param mobileNumber {String} The mobile number of the recipient of the SMS message, using the international E164 (without the plus) format
   * @param submitTime {Number} The date and time the message was originally submitted for scheduled delivery, in the format YYYYMMDDHHmm.
   * @param scheduledSendTime {Number} The date and time the message is scheduled to be delivered to the recipient, in the format YYYYMMDDHHmm.
   * @param creditCost {Number} The number of credits deducted from your account for the SMS to this recipient.  This is the number of credits that will be refunded if you delete this scheduled message. 
   */
  var exports = function(apiMessageId, mobileNumber, submitTime, scheduledSendTime, creditCost) {
    var _this = this;

    _this['apiMessageId'] = apiMessageId;
    _this['mobileNumber'] = mobileNumber;
    _this['submitTime'] = submitTime;
    _this['scheduledSendTime'] = scheduledSendTime;
    _this['creditCost'] = creditCost;
  };

  /**
   * Constructs a <code>ScheduledMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScheduledMessage} obj Optional instance to populate.
   * @return {module:model/ScheduledMessage} The populated <code>ScheduledMessage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiMessageId')) {
        obj['apiMessageId'] = ApiClient.convertToType(data['apiMessageId'], 'Number');
      }
      if (data.hasOwnProperty('mobileNumber')) {
        obj['mobileNumber'] = ApiClient.convertToType(data['mobileNumber'], 'String');
      }
      if (data.hasOwnProperty('submitTime')) {
        obj['submitTime'] = ApiClient.convertToType(data['submitTime'], 'Number');
      }
      if (data.hasOwnProperty('scheduledSendTime')) {
        obj['scheduledSendTime'] = ApiClient.convertToType(data['scheduledSendTime'], 'Number');
      }
      if (data.hasOwnProperty('creditCost')) {
        obj['creditCost'] = ApiClient.convertToType(data['creditCost'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The WinSMS API Message Id identifying the SMS message.
   * @member {Number} apiMessageId
   */
  exports.prototype['apiMessageId'] = undefined;
  /**
   * The mobile number of the recipient of the SMS message, using the international E164 (without the plus) format
   * @member {String} mobileNumber
   */
  exports.prototype['mobileNumber'] = undefined;
  /**
   * The date and time the message was originally submitted for scheduled delivery, in the format YYYYMMDDHHmm.
   * @member {Number} submitTime
   */
  exports.prototype['submitTime'] = undefined;
  /**
   * The date and time the message is scheduled to be delivered to the recipient, in the format YYYYMMDDHHmm.
   * @member {Number} scheduledSendTime
   */
  exports.prototype['scheduledSendTime'] = undefined;
  /**
   * The number of credits deducted from your account for the SMS to this recipient.  This is the number of credits that will be refunded if you delete this scheduled message. 
   * @member {Number} creditCost
   */
  exports.prototype['creditCost'] = undefined;



  return exports;
}));


