/**
 * WinSMS
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorDetails', 'model/ShortcodeMessageResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorDetails'), require('../model/ShortcodeMessageResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Winsms) {
      root.Winsms = {};
    }
    root.Winsms.ShortcodeApi = factory(root.Winsms.ApiClient, root.Winsms.ErrorDetails, root.Winsms.ShortcodeMessageResponse);
  }
}(this, function(ApiClient, ErrorDetails, ShortcodeMessageResponse) {
  'use strict';

  /**
   * Shortcode service.
   * @module api/ShortcodeApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ShortcodeApi. 
   * @alias module:api/ShortcodeApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getShortCodeMessages operation.
     * @callback module:api/ShortcodeApi~getShortCodeMessagesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ShortcodeMessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of incoming short/long code messages 
     * ***Only available to users with a [WinSMS Short/Long Code](https://support.winsms.co.za/winsms-long-short-code-system/).*** Get a list of all incoming short/long code messages received by the account.  Only the first 100 incoming short/long code messages will be returned if no ***offset*** and ***limit*** parameters are specified. 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.offset ***Optional*** - The number of items to skip before starting to return results. Default 0. Minimum 0.  (default to 0)
     * @param {Number} opts.limit ***Optional*** - The number of items to return. Default 100. Minimum 1. Maximum 1000.  (default to 100)
     * @param {module:api/ShortcodeApi~getShortCodeMessagesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ShortcodeMessageResponse}
     */
    this.getShortCodeMessages = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'offset': opts['offset'],
        'limit': opts['limit'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['APIKeyHeader'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ShortcodeMessageResponse;

      return this.apiClient.callApi(
        '/shortcode/incoming', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
