/**
 * WinSMS
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorDetails', 'model/SubAccountsResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorDetails'), require('../model/SubAccountsResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Winsms) {
      root.Winsms = {};
    }
    root.Winsms.SubaccountsApi = factory(root.Winsms.ApiClient, root.Winsms.ErrorDetails, root.Winsms.SubAccountsResponse);
  }
}(this, function(ApiClient, ErrorDetails, SubAccountsResponse) {
  'use strict';

  /**
   * Subaccounts service.
   * @module api/SubaccountsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SubaccountsApi. 
   * @alias module:api/SubaccountsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getSubAccounts operation.
     * @callback module:api/SubaccountsApi~getSubAccountsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SubAccountsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of all Sub Accounts.
     * Get a list of all the Sub Accounts owned by the Main Account.
     * @param {module:api/SubaccountsApi~getSubAccountsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SubAccountsResponse}
     */
    this.getSubAccounts = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['APIKeyHeader'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SubAccountsResponse;

      return this.apiClient.callApi(
        '/subaccounts', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
