/**
 * WinSMS
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CreditBalanceResponse', 'model/CreditTransferDetails', 'model/CreditTransferResponse', 'model/DeleteScheduledResponse', 'model/DeletedMessageStatus', 'model/ErrorDetails', 'model/IncomingMessage', 'model/IncomingMessageResponse', 'model/IncomingOptoutMessage', 'model/MessageRecipientDetails', 'model/MessageRecipientResponse', 'model/MessageStatus', 'model/MessageStatusResponse', 'model/MessageStatusResponse1', 'model/NewMessageDetails', 'model/NewMessageResponse', 'model/OptoutMessageResponse', 'model/ScheduledMessage', 'model/ShortcodeMessage', 'model/ShortcodeMessageResponse', 'model/SubAccount', 'model/SubAccountsResponse', 'api/CreditsApi', 'api/ShortcodeApi', 'api/SmsApi', 'api/SubaccountsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CreditBalanceResponse'), require('./model/CreditTransferDetails'), require('./model/CreditTransferResponse'), require('./model/DeleteScheduledResponse'), require('./model/DeletedMessageStatus'), require('./model/ErrorDetails'), require('./model/IncomingMessage'), require('./model/IncomingMessageResponse'), require('./model/IncomingOptoutMessage'), require('./model/MessageRecipientDetails'), require('./model/MessageRecipientResponse'), require('./model/MessageStatus'), require('./model/MessageStatusResponse'), require('./model/MessageStatusResponse1'), require('./model/NewMessageDetails'), require('./model/NewMessageResponse'), require('./model/OptoutMessageResponse'), require('./model/ScheduledMessage'), require('./model/ShortcodeMessage'), require('./model/ShortcodeMessageResponse'), require('./model/SubAccount'), require('./model/SubAccountsResponse'), require('./api/CreditsApi'), require('./api/ShortcodeApi'), require('./api/SmsApi'), require('./api/SubaccountsApi'));
  }
}(function(ApiClient, CreditBalanceResponse, CreditTransferDetails, CreditTransferResponse, DeleteScheduledResponse, DeletedMessageStatus, ErrorDetails, IncomingMessage, IncomingMessageResponse, IncomingOptoutMessage, MessageRecipientDetails, MessageRecipientResponse, MessageStatus, MessageStatusResponse, MessageStatusResponse1, NewMessageDetails, NewMessageResponse, OptoutMessageResponse, ScheduledMessage, ShortcodeMessage, ShortcodeMessageResponse, SubAccount, SubAccountsResponse, CreditsApi, ShortcodeApi, SmsApi, SubaccountsApi) {
  'use strict';

  /**
   * The full fucking description of the JavaScript Client.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Winsms = require('index'); // See note below*.
   * var xxxSvc = new Winsms.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Winsms.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Winsms.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Winsms.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CreditBalanceResponse model constructor.
     * @property {module:model/CreditBalanceResponse}
     */
    CreditBalanceResponse: CreditBalanceResponse,
    /**
     * The CreditTransferDetails model constructor.
     * @property {module:model/CreditTransferDetails}
     */
    CreditTransferDetails: CreditTransferDetails,
    /**
     * The CreditTransferResponse model constructor.
     * @property {module:model/CreditTransferResponse}
     */
    CreditTransferResponse: CreditTransferResponse,
    /**
     * The DeleteScheduledResponse model constructor.
     * @property {module:model/DeleteScheduledResponse}
     */
    DeleteScheduledResponse: DeleteScheduledResponse,
    /**
     * The DeletedMessageStatus model constructor.
     * @property {module:model/DeletedMessageStatus}
     */
    DeletedMessageStatus: DeletedMessageStatus,
    /**
     * The ErrorDetails model constructor.
     * @property {module:model/ErrorDetails}
     */
    ErrorDetails: ErrorDetails,
    /**
     * The IncomingMessage model constructor.
     * @property {module:model/IncomingMessage}
     */
    IncomingMessage: IncomingMessage,
    /**
     * The IncomingMessageResponse model constructor.
     * @property {module:model/IncomingMessageResponse}
     */
    IncomingMessageResponse: IncomingMessageResponse,
    /**
     * The IncomingOptoutMessage model constructor.
     * @property {module:model/IncomingOptoutMessage}
     */
    IncomingOptoutMessage: IncomingOptoutMessage,
    /**
     * The MessageRecipientDetails model constructor.
     * @property {module:model/MessageRecipientDetails}
     */
    MessageRecipientDetails: MessageRecipientDetails,
    /**
     * The MessageRecipientResponse model constructor.
     * @property {module:model/MessageRecipientResponse}
     */
    MessageRecipientResponse: MessageRecipientResponse,
    /**
     * The MessageStatus model constructor.
     * @property {module:model/MessageStatus}
     */
    MessageStatus: MessageStatus,
    /**
     * The MessageStatusResponse model constructor.
     * @property {module:model/MessageStatusResponse}
     */
    MessageStatusResponse: MessageStatusResponse,
    /**
     * The MessageStatusResponse1 model constructor.
     * @property {module:model/MessageStatusResponse1}
     */
    MessageStatusResponse1: MessageStatusResponse1,
    /**
     * The NewMessageDetails model constructor.
     * @property {module:model/NewMessageDetails}
     */
    NewMessageDetails: NewMessageDetails,
    /**
     * The NewMessageResponse model constructor.
     * @property {module:model/NewMessageResponse}
     */
    NewMessageResponse: NewMessageResponse,
    /**
     * The OptoutMessageResponse model constructor.
     * @property {module:model/OptoutMessageResponse}
     */
    OptoutMessageResponse: OptoutMessageResponse,
    /**
     * The ScheduledMessage model constructor.
     * @property {module:model/ScheduledMessage}
     */
    ScheduledMessage: ScheduledMessage,
    /**
     * The ShortcodeMessage model constructor.
     * @property {module:model/ShortcodeMessage}
     */
    ShortcodeMessage: ShortcodeMessage,
    /**
     * The ShortcodeMessageResponse model constructor.
     * @property {module:model/ShortcodeMessageResponse}
     */
    ShortcodeMessageResponse: ShortcodeMessageResponse,
    /**
     * The SubAccount model constructor.
     * @property {module:model/SubAccount}
     */
    SubAccount: SubAccount,
    /**
     * The SubAccountsResponse model constructor.
     * @property {module:model/SubAccountsResponse}
     */
    SubAccountsResponse: SubAccountsResponse,
    /**
     * The CreditsApi service constructor.
     * @property {module:api/CreditsApi}
     */
    CreditsApi: CreditsApi,
    /**
     * The ShortcodeApi service constructor.
     * @property {module:api/ShortcodeApi}
     */
    ShortcodeApi: ShortcodeApi,
    /**
     * The SmsApi service constructor.
     * @property {module:api/SmsApi}
     */
    SmsApi: SmsApi,
    /**
     * The SubaccountsApi service constructor.
     * @property {module:api/SubaccountsApi}
     */
    SubaccountsApi: SubaccountsApi
  };

  return exports;
}));
